spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/craft_beer
    username: beer
    password: Cr4ft@b33er
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true

server:
  port: 9000
  context-path: /beerhouse
