# Database
spring:
  spring:
    boot:
      admin:
        client:
          url: http://localhost:9000   # configurando o Spring Boot Admin Server

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/craft_beer
    username: postgres
    password: postgres

# JPA properties
  jpa:
    generate-ddl: true
    show-sql: true
    database: POSTGRESQL
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Server
server:
  port: 9000
  context-path: /beerhouse



#Actuator - endpoints customizadas
endpoints:
  context-path: /beerhouse
  beans:
    id: springbeans
  info:
    id: information
    sensitive: false # Habilita endpoints de dados mais sensíveis. Quando false recomandado usar algum tipo de autenticação na aplicação
    enabled: true
  shutdown:
    enabled: true # Fornece endpoint para desligar a aplicação. Não recomendado seu uso

# Desabilitando o spring secutiry
management:
  endpoint:
    info:
      enabled: true
  info:
    git:
      mode: full
      enabled: true
  security:
    enabled: false

#Adiciona informações ao enpoint info
info:
  app:
    name: @project.name@
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
