# Database
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/craft_beer
    username: postgres
    password: postgres

# JPA properties
  jpa:
    generate-ddl: true
    show-sql: true
    database: POSTGRESQL
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Server
server:
  servlet:
    context-path: /beerhouse
  port: 9000

#Actuator - endpoints customizados
management:
  info:
    git:
      mode: full # Habilita informações de versionamento da aplicaçõo no endpoint info
  endpoint:
    shutdown:
      enabled: true # Fornece endpoint para desligar a aplicação
    health:
     show-details: always
     metrics:
       enabled: false
     prometheus:
       enabled: true
  endpoints:
    web:
      base-path: /monitoring
      exposure:
        include: '*'
      path-mapping:
        info: information # Renomeando endpoint info
        beans: springbeans # Renomeando endpoint beans
  metrics:  # Prometheus
    export:
      prometheus:
        enabled: true

#Adiciona informações ao endpoint info
info:
  app:
    name: @project.name@
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
