# Database
spring:
  spring:
    boot:
      admin:
        client:
          url: http://localhost:9000   # configurando o Spring Boot Admin Server

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/craft_beer
    username: postgres
    password: postgres

# JPA properties
  jpa:
    generate-ddl: true
    show-sql: true
    database: POSTGRESQL
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Server
server:
  port: 9000
  context-path: /beerhouse

management:
  security:
    enabled: false

#Actuator - endpoints customizadas
endpoints:
  context-path: /beerhouse
  beans:
    id: springbeans
  info:
    id: information
    sensitive: false
    enabled: true
  shutdown:
    enabled: true

